version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: nikhil7841/docker-react
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/nikhils778/docker-react/environment-variables
          username: $USR_NAME
          password: $USR_KEY
jobs:
  my-job-name:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          docker run nikhil7841/docker-react npm run test -- --coverage

workflows:
  my-custom-workflow:
    jobs:
      - my-job-name