version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: |
            docker build -t nikhil7841/docker-app -f  dockerfile.dev .
      - run:
          name: Run tests
          command: |
            docker run -it nikhil7841/docker-app npm run test -- --coverage --watchAll=false

