version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update && sudo apt-get install -y docker
      - run:
          name: Build image
          command: |
            docker build -t nikhil7841/docker-app dockerfile.dev
      - run:
          name: Run tests
          command: |
            docker run -it nikhil7841/docker-app npm run test -- --coverage

